baseURL = "https://SnickersDE.github.io/Fussballgenie.de/"
languageCode = "de-DE"
title = "FussballGenie.de"
theme = ""
paginate = 12

[params]
  description = "Die schnellsten Bundesliga News — 1. & 2. Bundesliga"
  author = "Redaktion ZDSWD"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  artikel = "/artikel/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 10
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "title"
    weight = 100
